### ISSUE TITLE
Release Ready Checklist

### ISSUE THREAD

**Issue by worldpwn** [lostwood-games/website#3]
- [ ] Marketing campaign is started a year before.
- [ ] We did A/B tests for demo + ads. And content + steam page is spik and span.
- [ ] We are ready for upcoming events in Steam (e.g. Christmas, Helloween)
- [ ] We've decided what to do about SKU (The Cargo EA).
- [ ]
